# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '3.4'
services:
  phabricator:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    entrypoint: /app/entrypoint.sh
    command: test-ext
    environment:
      - MYSQL_HOST=phabdb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
    restart: on-failure
    depends_on:
      - phabdb

  phabdb:
    image: mysql:5.7
    volumes:
      - ./docker/phabricator/mysql:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
