# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  # BMO Containers
  bmo.test:
    image: mozillabteam/bmo
    command: demo
    volumes:
      - bmo-data-dir:/app/data
    environment: &bmo_env
      - LOCALCONFIG_ENV=1
      - BUGZILLA_UNSAFE_AUTH_DELEGATION=1
      - PORT=80
      - BMO_db_host=bmodb
      - BMO_db_name=bugs
      - BMO_db_user=bugs
      - BMO_db_pass=bugs
      - BMO_memcached_namespace=bugzilla
      - BMO_memcached_servers=memcached:11211
      - BMO_urlbase=http://bmo.test/
      - 'BMO_inbound_proxies=*'
      - BZ_QA_ANSWERS_FILE=/app/.circleci/checksetup_answers.txt
      - CONDUIT_USER_LOGIN=conduit@mozilla.bugs
      - CONDUIT_USER_PASSWORD=password123456789!
      - CONDUIT_USER_API_KEY=zQ5TSBzq7tTZMtKYq9K1ZqJMjifKx3cPL7pIGk9Q
      - PHABRICATOR_BOT_LOGIN=phab-bot@bmo.tld
      - PHABRICATOR_BOT_PASSWORD=password123456789!
      - PHABRICATOR_BOT_API_KEY=8G4ly8JkxbypZgh5XrdiHWExVEjPq5S3HvMBll1K
      - PHABRICATOR_API_KEY=api-qdaethogwpld3wmn2cnhbh57wkux
      - PHABRICATOR_APP_ID=66365490f364fbafba439619f0f31b7a4a0d73528c485520adf3b295f934acda
      - PHABRICATOR_AUTH_CALLBACK_URL=http://phabricator.test/auth/login/bmo:bmo.test/
    depends_on:
      - bmodb
      - memcached

  bmo.feed:
    image: mozillabteam/bmo
    command:
      - perl
      - extensions/PhabBugz/bin/phabbugz_feed.pl
      - start
      - '-d'
      - '-f'
    volumes:
      - bmo-data-dir:/app/data
    environment: *bmo_env
    restart: on-failure
    depends_on:
      - phabricator.test
      - bmodb
      - memcached

  bmo.pushd:
    image: mozillabteam/bmo
    command:
      - perl
      - extensions/Push/bin/bugzilla-pushd.pl
      - start
      - '-d'
      - '-f'
    volumes:
      - bmo-data-dir:/app/data
    environment: *bmo_env
    restart: on-failure
    depends_on:
      - phabricator.test
      - bmodb
      - memcached

  bmodb:
    image: mozillabteam/bmo-mysql:5.6
    volumes:
      - bmo-mysql-db:/var/lib/mysql
    logging:
      driver: "none"
    environment:
      - MYSQL_DATABASE=bugs
      - MYSQL_USER=bugs
      - MYSQL_PASSWORD=bugs
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  memcached:
    image: memcached:latest


# Volume Containers
volumes:
  bmo-mysql-db:
  bmo-data-dir:
